// 电影级分镜与运镜手册的结构化数据，来源于用户上传的《AI 视频电影级分镜与运镜手册》。
// 纯静态参考数据，不依赖后端，直接内嵌进前端：写分镜的画面描述(drawPrompt)/景别
// (sceneType)/运镜描述(motionPrompt)时，可以在这里搜索对应术语，点「复制」粘贴到
// 输入框里，不用来回切到手册原文件里找词。

export interface ManualEntry {
  zh: string
  en: string
  sub?: string // 子分类标签（比如运镜类目下的"山脉""CBD 商务区"），同一个 tab 内按 sub 分组展示
  extra?: string // 补充说明：原理/适用场景/效果
}

export interface ManualTab {
  id: string
  label: string
  entries: ManualEntry[]
}

export const CINEMATOGRAPHY_MANUAL: ManualTab[] = [
  {
    id: 'shotSize',
    label: '景别',
    entries: [
      { zh: '超远景 Extreme Wide Shot', en: 'extreme wide shot', extra: '展示自然环境/建立世界观/开场镜头；适用山脉、草原、雪山、大海、城市天际线；慢速，5-8秒，电影感★★★★★' },
      { zh: '大远景 Wide Shot', en: 'wide shot', extra: '展示人与环境的空间关系；慢速；适合纪录片/城市宣传片/旅行大片' },
      { zh: '全景 Full Shot', en: 'full shot', extra: '人物完整入镜，约占画面60%；适合城市街拍/商务/时尚/旅行Vlog' },
      { zh: '中景 Medium Shot', en: 'medium shot', extra: '人物腰部以上入镜；适合采访/解说/商业宣传/人物故事' },
      { zh: '近景 Close Up', en: 'close up', extra: '人物胸部以上入镜，突出情绪、眼神与细节' },
      { zh: '特写 Extreme Close Up', en: 'extreme close up', extra: '适合珠宝/医美/护肤/高端产品的细节展示' }
    ]
  },
  {
    // 注意：这个分类不是原手册里的内容——原手册偏"镜头语言"(景别/运镜/构图等)，没有覆盖
    // "表演/情绪基调"这一维度。这里补充一份通用的情绪/表情参考词，给 Shot.emotion 字段用，
    // 跟 sceneType(景别) 同一个使用模式：镜头列表里的独立小字段，不跟 drawPrompt 混写。
    id: 'emotion',
    label: '情绪',
    entries: [
      { sub: '正向', zh: '喜悦 / 欣喜', en: 'joyful, delighted expression' },
      { sub: '正向', zh: '期待 / 憧憬', en: 'hopeful, anticipating expression' },
      { sub: '正向', zh: '释然 / 平静', en: 'relieved, calm expression' },
      { sub: '正向', zh: '自豪 / 坚定', en: 'proud, determined expression' },
      { sub: '正向', zh: '温柔 / 眷恋', en: 'tender, affectionate expression' },
      { sub: '负向', zh: '悲伤 / 哀伤', en: 'sad, sorrowful expression' },
      { sub: '负向', zh: '愤怒 / 压抑的怒气', en: 'angry, suppressed rage expression' },
      { sub: '负向', zh: '恐惧 / 惊慌', en: 'fearful, panicked expression' },
      { sub: '负向', zh: '绝望 / 崩溃边缘', en: 'despairing, on the verge of breaking down' },
      { sub: '负向', zh: '羞愧 / 内疚', en: 'ashamed, guilty expression' },
      { sub: '负向', zh: '厌恶 / 嫌弃', en: 'disgusted, repulsed expression' },
      { sub: '复杂/张力', zh: '紧张 / 提心吊胆', en: 'tense, nervous expression' },
      { sub: '复杂/张力', zh: '震惊 / 难以置信', en: 'shocked, disbelieving expression' },
      { sub: '复杂/张力', zh: '怀疑 / 警惕', en: 'suspicious, wary expression' },
      { sub: '复杂/张力', zh: '挣扎 / 犹豫不决', en: 'conflicted, hesitant expression' },
      { sub: '复杂/张力', zh: '麻木 / 强装镇定', en: 'numb, forcing composure' },
      { sub: '中性/克制', zh: '冷静 / 不动声色', en: 'composed, expressionless, stoic' },
      { sub: '中性/克制', zh: '疏离 / 心不在焉', en: 'detached, distracted expression' }
    ]
  },
  {
    id: 'movement',
    label: '运镜',
    entries: [
      // 按景别推荐运镜（第一章）
      { sub: '超远景推荐运镜', zh: '无人机垂直升空', en: 'drone rise' },
      { sub: '超远景推荐运镜', zh: '无人机高速后退', en: 'drone pull back' },
      { sub: '超远景推荐运镜', zh: '超高空环绕', en: 'high altitude orbit' },
      { sub: '超远景推荐运镜', zh: '升降摇臂上摇', en: 'crane up' },
      { sub: '超远景推荐运镜', zh: '遮挡后揭示主体', en: 'reveal shot' },
      { sub: '大远景推荐运镜', zh: '缓慢向前推进', en: 'slow dolly in' },
      { sub: '大远景推荐运镜', zh: '缓慢向后拉远', en: 'slow dolly out' },
      { sub: '大远景推荐运镜', zh: '横移向左', en: 'truck left' },
      { sub: '大远景推荐运镜', zh: '横移向右', en: 'truck right' },
      { sub: '大远景推荐运镜', zh: '环绕运动', en: 'orbit' },
      { sub: '大远景推荐运镜', zh: '向前推进', en: 'push forward' },
      { sub: '全景推荐运镜', zh: '跟踪运镜', en: 'tracking shot' },
      { sub: '全景推荐运镜', zh: '侧向跟踪', en: 'side tracking' },
      { sub: '全景推荐运镜', zh: '跟随镜头', en: 'follow shot' },
      { sub: '全景推荐运镜', zh: '行走跟随', en: 'walk follow' },
      { sub: '全景推荐运镜', zh: '稳定器跟随', en: 'gimbal follow' },
      { sub: '全景推荐运镜', zh: '斯坦尼康稳定跟随', en: 'steadicam' },
      { sub: '中景推荐运镜', zh: '缓慢推进', en: 'slow push in' },
      { sub: '中景推荐运镜', zh: '弧形运镜', en: 'arc shot' },
      { sub: '中景推荐运镜', zh: '手持电影感晃动', en: 'handheld cinematic' },
      { sub: '中景推荐运镜', zh: '稳定器行走镜头', en: 'gimbal walk' },
      { sub: '近景推荐运镜', zh: '微型轨道推移', en: 'micro dolly' },
      { sub: '近景推荐运镜', zh: '平视视角', en: 'eye level' },
      { sub: '近景推荐运镜', zh: '人像环绕', en: 'portrait orbit' },
      { sub: '近景推荐运镜', zh: '面部追踪', en: 'face tracking' },
      { sub: '近景推荐运镜', zh: '镜头焦点拉伸', en: 'lens focus pull' },
      { sub: '特写推荐运镜', zh: '微距镜头', en: 'macro lens' },
      { sub: '特写推荐运镜', zh: '焦点拉伸', en: 'focus pull' },
      { sub: '特写推荐运镜', zh: '眼部特写', en: 'eye close' },
      { sub: '特写推荐运镜', zh: '唇部特写', en: 'lip close' },
      { sub: '特写推荐运镜', zh: '手部细节', en: 'hand detail' },
      { sub: '特写推荐运镜', zh: '珠宝细节', en: 'jewelry detail' },
      // 山水大片运镜（第二章）
      { sub: '山脉', zh: '无人机环绕', en: 'drone orbit' },
      { sub: '山脉', zh: '无人机拉远', en: 'drone pull away' },
      { sub: '山脉', zh: '缓慢揭示', en: 'slow reveal' },
      { sub: '山脉', zh: '穿越山脉', en: 'mountain fly through' },
      { sub: '山脉', zh: '穿云飞行', en: 'cloud fly' },
      { sub: '山脉', zh: '雾气揭示', en: 'mist reveal' },
      { sub: '山脉', zh: '日出延时', en: 'sunrise timelapse' },
      { sub: '山脉', zh: '黄金时刻', en: 'golden hour' },
      { sub: '山脉', zh: '史诗电影感', en: 'epic cinematic' },
      { sub: '湖泊', zh: '低空飞行', en: 'low fly' },
      { sub: '湖泊', zh: '掠水飞行', en: 'water skimming' },
      { sub: '湖泊', zh: '倒影镜头', en: 'reflection shot' },
      { sub: '湖泊', zh: '缓慢环绕', en: 'slow orbit' },
      { sub: '湖泊', zh: '横跨水面推进', en: 'push across water' },
      { sub: '湖泊', zh: '晨雾', en: 'morning fog' },
      { sub: '河流', zh: '无人机沿河追随', en: 'drone follow river' },
      { sub: '河流', zh: '正顶俯拍', en: 'top down' },
      { sub: '河流', zh: '穿越桥洞', en: 'bridge fly through' },
      { sub: '河流', zh: '曲线跟踪', en: 'curve tracking' },
      { sub: '河流', zh: '流动运动感', en: 'flow motion' },
      { sub: '森林', zh: 'FPV 第一视角穿越', en: 'fpv fly through' },
      { sub: '森林', zh: '树木揭示', en: 'tree reveal' },
      { sub: '森林', zh: '丁达尔光束', en: 'sunlight beam' },
      { sub: '森林', zh: '雾中追踪', en: 'fog tracking' },
      { sub: '森林', zh: '地面轨道推移', en: 'ground dolly' },
      { sub: '森林', zh: '低角度仰拍', en: 'low angle' },
      { sub: '海边', zh: '追浪运镜', en: 'wave tracking' },
      { sub: '海边', zh: '沙滩行走跟随', en: 'beach walk follow' },
      { sub: '海边', zh: '无人机绕圈', en: 'drone circle' },
      { sub: '海边', zh: '日落环绕', en: 'sunset orbit' },
      { sub: '海边', zh: '缓慢拉远', en: 'slow pull away' },
      // 城市大片运镜（第三章）
      { sub: '城市航拍', zh: '超延时摄影', en: 'hyperlapse' },
      { sub: '城市航拍', zh: '延时摄影', en: 'time lapse' },
      { sub: '城市航拍', zh: '城市揭示', en: 'city reveal' },
      { sub: '城市航拍', zh: '天际线拉远', en: 'skyline pull back' },
      { sub: '城市航拍', zh: '夜城', en: 'night city' },
      { sub: '城市航拍', zh: '赛博朋克风格', en: 'cyberpunk' },
      { sub: 'CBD 商务区', zh: '玻璃幕墙反射', en: 'glass reflection' },
      { sub: 'CBD 商务区', zh: '建筑揭示', en: 'building reveal' },
      { sub: 'CBD 商务区', zh: '快速推进', en: 'fast push' },
      { sub: 'CBD 商务区', zh: '垂直上升', en: 'vertical rise' },
      { sub: 'CBD 商务区', zh: '向上仰拍摇移', en: 'tilt up' },
      { sub: 'CBD 商务区', zh: '塔楼环绕', en: 'orbit tower' },
      { sub: '街道', zh: '行走跟随', en: 'walking follow' },
      { sub: '街道', zh: '街道跟踪', en: 'street tracking' },
      { sub: '街道', zh: '侧向推移', en: 'side dolly' },
      { sub: '街道', zh: '斑马线穿越', en: 'cross walk' },
      { sub: '街道', zh: '低角度追踪', en: 'low tracking' },
      { sub: '街道', zh: '雨地倒影', en: 'rain reflection' },
      { sub: '街道', zh: '霓虹夜景', en: 'night neon' },
      { sub: '商场', zh: '扶梯揭示', en: 'escalator reveal' },
      { sub: '商场', zh: '奢华跟踪', en: 'luxury tracking' },
      { sub: '商场', zh: '流畅推移', en: 'smooth dolly' },
      { sub: '商场', zh: '时尚步行', en: 'fashion walk' },
      // 人物时尚运镜（第四章）
      { sub: '女生街拍', zh: '慢速行走', en: 'slow walk' },
      { sub: '女生街拍', zh: '发丝飘动', en: 'hair motion' },
      { sub: '女生街拍', zh: '微笑特写', en: 'smile close up' },
      { sub: '女生街拍', zh: '转身镜头', en: 'turn around' },
      { sub: '女生街拍', zh: '风吹效果', en: 'wind effect' },
      { sub: '女生街拍', zh: '逆光拍摄', en: 'backlight' },
      { sub: '男士商务', zh: '西装行走', en: 'suit walk' },
      { sub: '男士商务', zh: '自信步态', en: 'confident walk' },
      { sub: '男士商务', zh: '现代建筑背景', en: 'modern building' },
      { sub: '男士商务', zh: 'CEO 风格', en: 'ceo style' },
      { sub: '医美宣传', zh: '美妆特写', en: 'beauty close' },
      { sub: '医美宣传', zh: '皮肤细节', en: 'skin detail' },
      { sub: '医美宣传', zh: '镜头耀光', en: 'lens flare' },
      { sub: '医美宣传', zh: '白色极简', en: 'white minimal' },
      { sub: '模特大片', zh: '猫步走秀', en: 'catwalk' },
      { sub: '模特大片', zh: '85mm 人像镜头', en: '85mm portrait' },
      { sub: '模特大片', zh: '眼神接触', en: 'eye contact' },
      { sub: '模特大片', zh: '编辑大片风格', en: 'editorial' },
      // 高级电影运镜合集（第五章，覆盖最全，推荐权重最高）
      { sub: '高级电影运镜合集', zh: '缓慢向前推轨（渐进逼近，营造张力）', en: 'slow dolly in' },
      { sub: '高级电影运镜合集', zh: '缓慢向后拉轨（渐进疏远，产生孤独感）', en: 'slow dolly out' },
      { sub: '高级电影运镜合集', zh: '环绕运镜（以主体为圆心环绕拍摄）', en: 'orbit' },
      { sub: '高级电影运镜合集', zh: '弧形运镜（半圆弧形轨迹移动）', en: 'arc shot' },
      { sub: '高级电影运镜合集', zh: '推进镜头（向主体快速推近）', en: 'push in' },
      { sub: '高级电影运镜合集', zh: '推出镜头（从主体快速拉远）', en: 'push out' },
      { sub: '高级电影运镜合集', zh: '向左横移', en: 'truck left' },
      { sub: '高级电影运镜合集', zh: '向右横移', en: 'truck right' },
      { sub: '高级电影运镜合集', zh: '向上仰摇', en: 'tilt up' },
      { sub: '高级电影运镜合集', zh: '向下俯摇', en: 'tilt down' },
      { sub: '高级电影运镜合集', zh: '向左摇镜', en: 'pan left' },
      { sub: '高级电影运镜合集', zh: '向右摇镜', en: 'pan right' },
      { sub: '高级电影运镜合集', zh: '摇臂上升', en: 'crane up' },
      { sub: '高级电影运镜合集', zh: '摇臂下降', en: 'crane down' },
      { sub: '高级电影运镜合集', zh: '揭示镜头（从遮挡后展示主体）', en: 'reveal shot' },
      { sub: '高级电影运镜合集', zh: 'FPV 穿越拍摄（第一人称视角穿越场景）', en: 'fpv fly through' },
      { sub: '高级电影运镜合集', zh: '正顶俯拍', en: 'top down' },
      { sub: '高级电影运镜合集', zh: '头顶俯视（高角度俯瞰）', en: 'overhead' },
      { sub: '高级电影运镜合集', zh: '荷兰角倾斜（制造不安定感）', en: 'dutch angle' },
      { sub: '高级电影运镜合集', zh: '手持电影感（轻微晃动增加真实感）', en: 'handheld cinematic' },
      { sub: '高级电影运镜合集', zh: '斯坦尼康稳拍', en: 'steadicam' },
      { sub: '高级电影运镜合集', zh: '超延时摄影（移动中的快速延时）', en: 'hyperlapse' },
      { sub: '高级电影运镜合集', zh: '对焦切换（快速在两个焦点间切换）', en: 'rack focus' },
      { sub: '高级电影运镜合集', zh: '镜头压缩（长焦压缩空间层次感）', en: 'lens compression' },
      { sub: '高级电影运镜合集', zh: '视差运镜（前后景位移产生视差）', en: 'parallax' },
      { sub: '高级电影运镜合集', zh: '速度渐变（快慢速度交替变化）', en: 'speed ramp' },
      { sub: '高级电影运镜合集', zh: '慢动作（高帧率拍摄慢速回放）', en: 'slow motion' }
    ]
  },
  {
    id: 'transition',
    label: '转场',
    entries: [
      { sub: '基础物理类', zh: '1. 甩镜转场 — 快速横向摇摄，用运动模糊隐藏剪辑点', en: 'whip pan transition' },
      { sub: '基础物理类', zh: '2. 匹配剪辑 — 相似形状或动作直接切换（如球→地球）', en: 'match cut' },
      { sub: '基础物理类', zh: '3. 动作匹配剪辑 — 人物动作一致时切换', en: 'motion match cut' },
      { sub: '基础物理类', zh: '4. 穿越推进转场 — 镜头推进到物体内部完成切换', en: 'push through transition' },
      { sub: '基础物理类', zh: '5. 拉远转场 — 从细节画面拉远到全新场景', en: 'pull out transition' },
      { sub: '基础物理类', zh: '6. 旋转转场 — 镜头旋转360°切换场景', en: 'spin transition' },
      { sub: '基础物理类', zh: '7. 缩放模糊转场 — 快速缩放叠加模糊切换', en: 'zoom blur transition' },
      { sub: '基础物理类', zh: '8. 抖动切换 — 用手持抖动隐藏剪辑点', en: 'camera shake cut' },
      { sub: '基础物理类', zh: '9. 焦点转场 — 前景虚化→后景清晰→切换', en: 'rack focus transition' },
      { sub: '基础物理类', zh: '10. 遮挡切换 — 物体遮挡镜头瞬间完成切换', en: 'object occlusion cut' },
      { sub: '基础物理类', zh: '11. 镜头甩切 — 镜头快速摆动完成过渡', en: 'lens whip transition' },
      { sub: '基础物理类', zh: '12. 冲击剪辑 — 撞击瞬间切换（关门/拳击/爆炸）', en: 'impact cut' },
      { sub: '空间连续类', zh: '13. 开门转场 — 打开门瞬间进入另一世界', en: 'door transition' },
      { sub: '空间连续类', zh: '14. 窗景切换 — 透过窗户看到全新场景', en: 'window reveal' },
      { sub: '空间连续类', zh: '15. 镜子转场 — 镜中世界与现实世界切换', en: 'mirror transition' },
      { sub: '空间连续类', zh: '16. 水面转场 — 跳入水中进入新场景空间', en: 'water surface transition' },
      { sub: '空间连续类', zh: '17. 烟雾溶解转场 — 烟雾遮挡后画面切换', en: 'smoke dissolve' },
      { sub: '空间连续类', zh: '18. 雾中显现转场 — 雾气散开后显现新画面', en: 'fog reveal' },
      { sub: '空间连续类', zh: '19. 隧道穿越转场 — 穿过隧道进入城市或山景', en: 'tunnel pass-through' },
      { sub: '空间连续类', zh: '20. 帘幕转场 — 拉开幕布后进入新场景', en: 'curtain reveal' },
      { sub: '空间连续类', zh: '21. 电梯转场 — 电梯门打开即进入新世界', en: 'lift / elevator transition' },
      { sub: '空间连续类', zh: '22. 楼梯转场 — 上下楼梯切换进入不同空间', en: 'staircase transition' },
      { sub: '空间连续类', zh: '23. 车窗过渡转场 — 车窗外景变化完成切换', en: 'train / car pass-by' },
      { sub: '空间连续类', zh: '24. 传送门转场 — 空间裂缝式进入新场景', en: 'portal transition' },
      { sub: '动态运镜融合类', zh: '25. 无人机穿越转场 — 穿越楼宇或山脉直接切换', en: 'drone fly-through transition' },
      { sub: '动态运镜融合类', zh: '26. FPV 高速切换 — 第一视角高速飞行中完成切换', en: 'fpv speed transition' },
      { sub: '动态运镜融合类', zh: '27. 环绕切换 — 环绕人物360°过程中切换场景', en: 'orbit cut' },
      { sub: '动态运镜融合类', zh: '28. 弧线匹配转场 — 相同弧形运动轨迹中完成切换', en: 'arc match transition' },
      { sub: '动态运镜融合类', zh: '29. 跟拍连续切 — 保持跟拍运动连续性无感切换', en: 'tracking continuity cut' },
      { sub: '动态运镜融合类', zh: '30. 稳定器行走切换 — 稳定器行走运动中过渡', en: 'gimbal walk transition' },
      { sub: '动态运镜融合类', zh: '31. 俯拍落切 — 从高处正俯拍快速下降完成切换', en: 'overhead drop cut' },
      { sub: '动态运镜融合类', zh: '32. 摇臂升降切换 — 摇臂升降过程中切换场景', en: 'crane up / down cut' },
      { sub: '动态运镜融合类', zh: '33. 横移平行切 — 摄像机横向平移中完成过渡', en: 'side slide transition' },
      { sub: '动态运镜融合类', zh: '34. 前进惯性切换 — 保持向前运动惯性中完成切换', en: 'forward momentum cut' },
      { sub: '动态运镜融合类', zh: '35. 后退拉镜切换 — 镜头持续后退过程中切换', en: 'reverse pull cut' },
      { sub: '动态运镜融合类', zh: '36. 视差环绕转场 — 前后景视差在环绕运动中过渡', en: 'circular parallax transition' },
      { sub: '视觉特效类', zh: '37. 闪光切换 — 强烈白光或亮光闪烁中切换', en: 'light flash transition' },
      { sub: '视觉特效类', zh: '38. 镜头光晕切换 — 用镜头耀光遮盖剪辑点', en: 'lens flare cut' },
      { sub: '视觉特效类', zh: '39. 故障风切换 — 数字信号故障感的画面跳切', en: 'glitch transition' },
      { sub: '视觉特效类', zh: '40. 扫描线切换 — 像扫描仪般从上至下扫过切换', en: 'digital scan transition' },
      { sub: '视觉特效类', zh: '41. 像素溶解转场 — 画面像素化后溶解进入新场景', en: 'pixel dissolve' },
      { sub: '视觉特效类', zh: '42. 粒子爆破转场 — 画面爆炸成粒子后切换', en: 'particle explosion transition' },
      { sub: '视觉特效类', zh: '43. 能量波动切换 — 能量波纹向外扩散中完成过渡', en: 'energy wave transition' },
      { sub: '视觉特效类', zh: '44. 霓虹闪烁切换 — 霓虹灯闪烁节拍中隐藏剪辑点', en: 'neon flicker cut' },
      { sub: '视觉特效类', zh: '45. 色彩分离切换 — RGB三色通道错位分离后切换', en: 'rgb split transition' },
      { sub: '电影级高级类', zh: '46. 时间扭曲转场 — 现实→慢动作→未来场景的跳跃', en: 'time warp transition' },
      { sub: '电影级高级类', zh: '47. 光影匹配切换 — 两场景光源方向一致隐藏剪辑点', en: 'match lighting transition' },
      { sub: '电影级高级类', zh: '48. 影子转场 — 影子移动过程中完成场景切换', en: 'shadow transition' },
      { sub: '电影级高级类', zh: '49. 折射转场 — 通过玻璃或水的折射效果切换', en: 'refraction transition' },
      { sub: '电影级高级类', zh: '50. 隐形剪辑 — 完全看不出剪辑点的极致无缝切换', en: 'invisible cut (hidden cut)' }
    ]
  },
  {
    id: 'composition',
    label: '构图',
    entries: [
      { zh: '三分法（画面横竖各分三份，主体置于交叉点，自然平衡感）', en: 'rule of thirds composition' },
      { zh: '黄金比例（1:1.618 螺旋线安排视觉焦点，最接近人眼审美）', en: 'golden ratio framing' },
      { zh: '对称构图（左右或上下对称，传达庄严/稳定/权威感）', en: 'symmetrical composition, centered' },
      { zh: '引导线构图（道路/走廊/河流等线条引导视线到主体）', en: 'leading lines composition' },
      { zh: '框中框（用门框/窗框/树洞二次框定主体，增加层次感）', en: 'frame within frame' },
      { zh: '负空间（大面积留白衬托主体，孤独/极简/高级感）', en: 'negative space, minimalist composition' },
      { zh: '对角线构图（对角线安排元素，产生动势与张力）', en: 'diagonal composition, dynamic' },
      { zh: '三角形构图（三点形成三角，画面稳定有力）', en: 'triangular composition' },
      { zh: '前景框架（利用前景元素增加空间纵深感）', en: 'foreground framing, depth' },
      { zh: '消失点构图（透视线汇聚一点，强烈空间纵深与震撼感）', en: 'vanishing point, one-point perspective' },
      { zh: '三层空间纵深（前景虚化+中景清晰主体+背景模糊环境）', en: 'rich foreground bokeh, sharp midground subject, blurred background, three-layer depth' }
    ]
  },
  {
    id: 'lighting',
    label: '灯光',
    entries: [
      { sub: '光线方向', zh: '顺光（均匀曝光，细节清晰，缺乏立体感）', en: 'front lighting, even illumination' },
      { sub: '光线方向', zh: '侧光/伦勃朗光（一半明一半暗，强烈立体感与戏剧张力）', en: 'side lighting, Rembrandt lighting' },
      { sub: '光线方向', zh: '逆光（轮廓光，主体剪影，梦幻感）', en: 'backlight, rim light, silhouette' },
      { sub: '光线方向', zh: '轮廓光（边缘发光，主体与背景分离，高端感）', en: 'rim lighting, edge light' },
      { sub: '光线方向', zh: '顶光（阴影向下，硬朗或恐怖感）', en: 'top lighting, overhead light' },
      { sub: '光线方向', zh: '底光（阴影向上，诡异或反常感）', en: 'under lighting, uplighting' },
      { sub: '光线方向', zh: '三点布光（主光+补光+轮廓光，最标准商业布光）', en: 'three-point lighting, studio setup' },
      { sub: '光线方向', zh: '蝴蝶光（鼻下蝴蝶形阴影，好莱坞女星光）', en: 'butterfly lighting, glamour lighting' },
      { sub: '光线性质', zh: '硬光（阴影边缘锐利，对比强，戏剧/悬疑/力量感）', en: 'hard light' },
      { sub: '光线性质', zh: '柔光（阴影过渡柔和，皮肤质感好，美妆/人像/医美）', en: 'soft light' },
      { sub: '光线性质', zh: '散射光（无明显阴影，均匀柔和，纪录片/日常）', en: 'diffused light' },
      { sub: '光线性质', zh: '镜面光（高光点明显，金属质感强，科技/奢品/汽车）', en: 'specular light' },
      { sub: '光线性质', zh: '环境光（来自四面的散漫光，室内写实场景）', en: 'ambient light' },
      { sub: '光线性质', zh: '实用光源（场景内真实光源如台灯霓虹，电影感/写实）', en: 'practical light' },
      { sub: '自然光时段', zh: '蓝调时刻（极冷5500-7000K，深蓝天空城市灯光刚亮）', en: 'blue hour, twilight, deep blue sky' },
      { sub: '自然光时段', zh: '黄金时刻·日出（暖橙2500-3500K，低角度暖光长影子）', en: 'golden hour sunrise, warm morning light' },
      { sub: '自然光时段', zh: '正午强光（中性5500K，顶光硬阴影重对比强）', en: 'harsh midday sun, high contrast' },
      { sub: '自然光时段', zh: '黄金时刻·日落（暖金2000-3000K，橙红长光最具电影感）', en: 'golden hour sunset, orange glow' },
      { sub: '自然光时段', zh: '蓝调黄昏（冷蓝紫6000K+，天空深蓝城市灯光全亮）', en: 'blue hour dusk, city lights, moody' },
      { sub: '自然光时段', zh: '夜晚（混合色温，人工光源主导高对比）', en: 'night scene, neon light, ambient glow' },
      { sub: '通用风格关键词', zh: '电影感', en: 'cinematic' },
      { sub: '通用风格关键词', zh: 'IMAX 画质', en: 'IMAX' },
      { sub: '通用风格关键词', zh: '好莱坞风格', en: 'Hollywood' },
      { sub: '通用风格关键词', zh: '大师级作品', en: 'masterpiece' },
      { sub: '通用风格关键词', zh: '超写实', en: 'ultra realistic' },
      { sub: '通用风格关键词', zh: '体积光', en: 'volumetric lighting' },
      { sub: '通用风格关键词', zh: '镜头耀光', en: 'lens flare' },
      { sub: '通用风格关键词', zh: '8K 超高清', en: '8K' },
      { sub: '通用风格关键词', zh: '专业电影摄影', en: 'professional cinematography' }
    ]
  },
  {
    id: 'color',
    label: '调色',
    entries: [
      { zh: '橙青对比（肤色偏橙阴影偏青，好莱坞最流行，如《变形金刚》）', en: 'orange and teal color grading' },
      { zh: '哑光胶片（黑位提升低对比，复古胶片感，文艺片/旅拍）', en: 'matte film look' },
      { zh: '去饱和写实（低饱和度接近真实，纪录片/战争片）', en: 'desaturated realistic' },
      { zh: '柯达胶片模拟（暖黄高光青色阴影粗颗粒，复古情感类）', en: 'Kodak film emulation, grain' },
      { zh: '富士胶片模拟（绿色偏移清新日系，皮肤粉嫩）', en: 'Fuji film emulation, pastel tones' },
      { zh: '青绿冷调（整体冷绿调，科技感疏离感）', en: 'teal and green color grading' },
      { zh: '高对比黑白（消色保留亮度，戏剧感强，艺术/人文）', en: 'high contrast black and white' },
      { zh: '赛博霓虹（高饱和蓝紫粉，高对比夜景）', en: 'cyberpunk color grading, neon purple and cyan' },
      { zh: '极简清冷（高亮低饱和干净现代，奢品/医美/科技发布会）', en: 'minimal cool white, desaturated' },
      { zh: '暖棕复古（高光橙棕整体低饱和菲林感，怀旧品牌故事）', en: 'warm brown vintage LUT' },
      { zh: '互补色搭配（橙vs青、红vs绿，对比色张力强）', en: 'complementary color grading, orange and teal' },
      { zh: '类比色搭配（相邻色如橙黄暖调，和谐温暖）', en: 'analogous warm color palette' },
      { zh: '单色系搭配（同一色相不同明度，极简高级）', en: 'monochromatic color scheme, minimal' },
      { zh: '三色平衡搭配（三种等距色，活跃丰富）', en: 'triadic color balance, vibrant' },
      { zh: '分裂互补搭配（一色对两邻补色，既对比又和谐）', en: 'split complementary palette' }
    ]
  },
  {
    id: 'lens',
    label: '焦距/景深',
    entries: [
      { sub: '焦距', zh: '鱼眼/超广角 8-14mm（极度变形夸张透视，极限运动/创意艺术）', en: 'fisheye lens, extreme wide angle' },
      { sub: '焦距', zh: '超广角 14-24mm（宏大感，环境纳入多，建筑/风光/航拍）', en: 'ultra wide angle, 16mm lens' },
      { sub: '焦距', zh: '广角 24-35mm（接近人眼略带透视，街拍/纪录片/Vlog）', en: 'wide angle 24mm, street photography' },
      { sub: '焦距', zh: '标准镜头 50mm（最真实还原人眼视角，人文/日常/写实）', en: '50mm standard lens, natural perspective' },
      { sub: '焦距', zh: '人像镜头 85mm（浅景深压缩背景人脸比例最佳，人像/时尚/商业）', en: '85mm portrait lens, shallow depth of field' },
      { sub: '焦距', zh: '中长焦 100-135mm（强背景虚化奢华感，高端广告/人像）', en: '135mm lens, luxurious bokeh' },
      { sub: '焦距', zh: '长焦 200mm+（强透视压缩偷拍感空间扁平，体育/望远/新闻）', en: 'telephoto 200mm, compressed perspective' },
      { sub: '景深', zh: '浅景深（主体清晰背景大幅虚化，高级感强）', en: 'shallow depth of field, f1.8 bokeh, blurred background' },
      { sub: '景深', zh: '深景深（前后都清晰，展示环境细节）', en: 'deep depth of field, everything in focus, f11' },
      { sub: '景深', zh: '选择性对焦（仅特定平面清晰，引导视线）', en: 'selective focus, tilt-shift effect' },
      { sub: '焦外虚化', zh: '圆形光斑（柔和圆形，梦幻感）', en: 'circular bokeh, dreamy background blur' },
      { sub: '焦外虚化', zh: '猫眼虚化（边缘旋转感，艺术感强）', en: 'swirly bokeh, vintage lens' },
      { sub: '焦外虚化', zh: '六边形光斑（光圈叶片形状，工业感）', en: 'hexagonal bokeh, mechanical' },
      { sub: '焦外虚化', zh: '奶油虚化（极度平滑，奢华感）', en: 'creamy smooth bokeh, luxury' },
      { sub: '焦外虚化', zh: '前景虚化（前景光斑+清晰中景，增加层次）', en: 'foreground bokeh, depth layering' }
    ]
  },
  {
    id: 'editing',
    label: '镜头功能/剪辑',
    entries: [
      { sub: '功能性镜头', zh: '建立镜头（交代地点与环境，场景开头用）', en: 'establishing shot' },
      { sub: '功能性镜头', zh: '主镜头（完整展示场景全貌与人物关系，对话/群戏用）', en: 'master shot' },
      { sub: '功能性镜头', zh: '切出镜头（切离主场景补充信息或制造悬念）', en: 'cutaway shot' },
      { sub: '功能性镜头', zh: '插入镜头（聚焦细节：手/道具/屏幕，强调重要信息）', en: 'insert shot' },
      { sub: '功能性镜头', zh: '反应镜头（拍摄人物对事件的情绪反应）', en: 'reaction shot' },
      { sub: '功能性镜头', zh: '主观视角镜头（模拟角色视角，代入感强）', en: 'POV shot' },
      { sub: '功能性镜头', zh: '过肩镜头（从一方肩膀后拍另一方，对话常用）', en: 'over-the-shoulder' },
      { sub: '功能性镜头', zh: '双人镜头（两人同框，展示人物关系）', en: 'two shot' },
      { sub: '音画剪辑技法', zh: 'J 剪辑（下一镜头的声音先于画面出现，流畅过渡）', en: 'J-cut' },
      { sub: '音画剪辑技法', zh: 'L 剪辑（上一镜头声音延续到下一画面，情绪连贯）', en: 'L-cut' },
      { sub: '音画剪辑技法', zh: '动作中切（人物动作进行中切换镜头，无感知切换）', en: 'cut on action' },
      { sub: '音画剪辑技法', zh: '节拍剪辑（剪辑点与音乐节拍对齐，节奏感强）', en: 'beat cut' },
      { sub: '节奏/结构', zh: '快剪 1-2秒（活力/节奏感，广告/预告片）', en: 'fast cut' },
      { sub: '节奏/结构', zh: '标准节奏 3-5秒（自然流畅，宣传片/纪录片）', en: 'standard pacing' },
      { sub: '节奏/结构', zh: '慢节奏/长镜头 6秒以上（沉稳/史诗感/艺术感）', en: 'slow pacing, long take' }
    ]
  },
  {
    id: 'negative',
    label: '负面词汇',
    entries: [
      { sub: '通用', zh: '通用负面词（几乎所有场景适用：低质量/模糊/水印/文字/解剖错误/卡通/CGI）', en: 'lowres, blurry, out of focus, low quality, jpeg artifacts, compressed, watermark, text, logo, signature, username, frame, border, bad anatomy, deformed, mutated, extra limbs, disfigured, ugly, amateur, amateurish, overexposed, underexposed, cartoon, illustration, painting, drawing, anime, 3D render, unrealistic, fake, CGI, plastic, toy' },
      { sub: '企业宣传片', zh: '企业宣传片专用（排除人物/字幕/Logo/卡通插画）', en: 'people, humans, faces, portraits, bodies, crowds, text overlay, subtitles, captions, readable text, logo, brand name, watermark, illustration, cartoon, 3D render, abstract graphics' },
      { sub: '时尚人像', zh: '时尚人像专用（排除面部/手部畸变、过曝塑料感皮肤）', en: 'bad face, distorted face, asymmetrical eyes, extra fingers, bad hands, missing fingers, fused fingers, cropped head, overexposed skin, plastic skin, doll-like, uncanny valley' },
      { sub: '风景航拍', zh: '风景航拍专用（排除人物车辆电线杆/丑陋建筑/污染）', en: 'people, humans, vehicles in foreground, power lines, ugly buildings, construction site, garbage, pollution, overcast flat lighting, lens distortion, fisheye effect' }
    ]
  },
  {
    id: 'director',
    label: '导演风格',
    entries: [
      { zh: '斯坦利·库布里克 — 单点透视/对称构图/冷色调/缓慢推进', en: 'Kubrick one-point perspective, symmetrical, cold tones, slow dolly' },
      { zh: '王家卫 — 浅景深/慢速快门/暖橙霓虹/手持晃动', en: 'Wong Kar-wai style, shallow DOF, warm neon, slow shutter, moody' },
      { zh: '诺兰 — IMAX 宽银幕/高对比自然光/实拍感', en: 'Nolan IMAX cinematography, natural light, high contrast, practical' },
      { zh: '罗杰·迪金斯 — 精妙自然光/低调优雅/油画感构图', en: 'Roger Deakins lighting, painterly, natural side light, moody' },
      { zh: '维伦纽瓦 — 极简宏大/冷蓝沙漠色/超宽银幕', en: 'Villeneuve epic scale, minimal, cold blue palette, anamorphic' },
      { zh: '泽维尔·多兰 — 超慢动作/正面对称/高饱和暖调', en: 'Dolan style, slow motion, front facing, saturated warm tones' },
      { zh: '大卫·芬奇 — 极低光/绿褐色调/完美构图/压抑感', en: 'Fincher dark moody, green-brown tones, low key, precise framing' },
      { zh: '韦斯·安德森 — 极端对称/粉彩色调/俯拍/童话感', en: 'Wes Anderson symmetry, pastel palette, overhead shot, whimsical' },
      { zh: '阿方索·卡隆 — 长镜头/手持/自然光/强临场感', en: 'Cuaron long take, handheld, natural light, immersive' },
      { zh: '宫崎骏风格（动画参考）— 手绘质感/自然环境/柔和光线', en: 'Ghibli-inspired, painterly, nature, soft warm light' }
    ]
  }
]
